#[repr(usize)]
enum AuxEntry {
    End = 0,
    Ignore = 1,
    ExecFd(usize) = 2,
    Phdr(*const crate::elf::ProgramHeader) = 3,
    PhEnt(usize) = 4,
    PhNum(usize) = 5,
    PageSz(usize) = 6,
    Base(*const u8),
    Flags(usize),
    Entry(*const fn()),
    NotElf = 10,
    Uid(usize) = 11,
    EUid(usize) = 12,
    Gid(usize) = 13,
    EGid(usize) = 14,
    Platform(usize) = 15,
    HwCap(usize) = 16,
    ClkTck(usize) = 17,
    Secure(bool) = 23,
    BasePlatform(usize) = 24,
    Random(*const [u8; 16]) = 25,
    HwCap2(usize) = 26,
    ExecFn(*const str) = 31,
    MinSigStckSz(usize) = 51
}
